package com.Login.Security.Config;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.lang.NonNull;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
@Component
@RequiredArgsConstructor
public class JwtAuthenticationFilter extends OncePerRequestFilter {
    //autogenerate whe you create the methodmplementation class caled applicato config
    private final JwtService jwtServive;
    //UserDetailsService is an interface class autogenerated and need an im
    private UserDetailsService userDetailsService;

    @Override
    protected void doFilterInternal(
           @NonNull HttpServletRequest request,
           @NonNull HttpServletResponse response,
           @NonNull FilterChain filterChain
    ) throws ServletException, IOException {
        //Authorization is the header that has jwt token
        final String authHeader = request.getHeader("Authorization");
        final String jwt;
        final String userEmail;
        if (authHeader==null ||!authHeader.startsWith("Bearer ")){
            filterChain.doFilter(request, response);
            return;

        }
        //extracting the token from authorization header
        jwt = authHeader.substring(7);
      //todo extract the user-email from jwt token
        userEmail= jwtServive.extractUsername(jwt);
        if (userEmail !=null && SecurityContextHolder.getContext().getAuthentication()==null){
            //checking if user-exist in the database
            UserDetails userDetails = this.userDetailsService.loadUserByUsername(userEmail);
        }

    }
}
